"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 11:07:14.945176
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('avatar_hue', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('streak_freezes', sa.Integer(), nullable=False),
    sa.Column('show_on_leaderboards', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('quest', 'focus', 'achievement', 'challenge', 'shop', name='ledgersource', native_enum=False, length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=80), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('counts_for_streak', sa.Boolean(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger')),
    sa.UniqueConstraint('user_id', 'source_ref', name=op.f('uq_ledger_user_id_source_ref'))
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_ledger_user_date', ['user_id', 'local_date'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('read_at', app.db.base.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'dedupe_key', name=op.f('uq_notifications_user_id_dedupe_key'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=24), nullable=False),
    sa.Column('hue', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_parties_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parties')),
    sa.UniqueConstraint('invite_code', name=op.f('uq_parties_invite_code'))
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'normal', 'hard', 'legendary', name='difficulty', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', name='priority', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'failed', 'expired', name='queststatus', native_enum=False, length=20), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('due_at', app.db.base.UTCDateTime(), nullable=True),
    sa.Column('base_xp', sa.Integer(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=True),
    sa.Column('coins_awarded', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('started_at', app.db.base.UTCDateTime(), nullable=True),
    sa.Column('closed_at', app.db.base.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests'))
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_due_at'), ['due_at'], unique=False)
        batch_op.create_index('ix_quests_user_status', ['user_id', 'status'], unique=False)

    op.create_table('refresh_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('rotated_at', app.db.base.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', app.db.base.UTCDateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_sessions_token_hash'))
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('streak_freezes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_streak_freezes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streak_freezes')),
    sa.UniqueConstraint('user_id', 'day', name=op.f('uq_streak_freezes_user_id_day'))
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('unlocked_at', app.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements')),
    sa.UniqueConstraint('user_id', 'code', name=op.f('uq_user_achievements_user_id_code'))
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('focus_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='focusstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('ended_at', app.db.base.UTCDateTime(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_focus_sessions_quest_id_quests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_focus_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_focus_sessions'))
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_focus_user_status', ['user_id', 'status'], unique=False)

    op.create_table('party_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('metric', sa.Enum('quests_completed', 'focus_minutes', 'xp', name='challengemetric', native_enum=False, length=20), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('starts_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('ends_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'failed', name='challengestatus', native_enum=False, length=20), nullable=False),
    sa.Column('completed_at', app.db.base.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_party_challenges_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_party_challenges_party_id_parties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_challenges'))
    )
    with op.batch_alter_table('party_challenges', schema=None) as batch_op:
        batch_op.create_index('ix_party_challenges_party_status', ['party_id', 'status'], unique=False)

    op.create_table('party_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'cancelled', name='invitestatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(), nullable=False),
    sa.Column('responded_at', app.db.base.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], name=op.f('fk_party_invites_invitee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], name=op.f('fk_party_invites_inviter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_party_invites_party_id_parties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_invites'))
    )
    with op.batch_alter_table('party_invites', schema=None) as batch_op:
        batch_op.create_index('ix_party_invites_invitee', ['invitee_id', 'status'], unique=False)

    op.create_table('party_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='partyrole', native_enum=False, length=20), nullable=False),
    sa.Column('joined_at', app.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_party_members_party_id_parties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_party_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_members')),
    sa.UniqueConstraint('party_id', 'user_id', name=op.f('uq_party_members_party_id_user_id'))
    )
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.create_index('ix_party_members_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.drop_index('ix_party_members_user')

    op.drop_table('party_members')
    with op.batch_alter_table('party_invites', schema=None) as batch_op:
        batch_op.drop_index('ix_party_invites_invitee')

    op.drop_table('party_invites')
    with op.batch_alter_table('party_challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_party_challenges_party_status')

    op.drop_table('party_challenges')
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_focus_user_status')

    op.drop_table('focus_sessions')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))

    op.drop_table('user_achievements')
    op.drop_table('streak_freezes')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_family_id'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index('ix_quests_user_status')
        batch_op.drop_index(batch_op.f('ix_quests_due_at'))

    op.drop_table('quests')
    op.drop_table('parties')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_created')

    op.drop_table('notifications')
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_user_date')
        batch_op.drop_index('ix_ledger_user_created')

    op.drop_table('ledger')
    op.drop_table('users')
    # ### end Alembic commands ###
